browser=chrome
headless=true
host=local
hub.url=http://localhost:4444/wd/hub
browser.version=
timeout.explicit=20
timeout.pageLoad=60
retry.count=1

url.registration=https://demo.guru99.com/test/newtours/register.php
url.amazon=https://www.amazon.com
